#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CUSTOM_NO_RGB
#define DISABLE_RGB_MATRIX_SOLID_COLOR
#define RGB_DISABLE_WHEN_USB_SUSPENDED true // turn off effects when suspended

#define UNDERGLOW_START 67
#define TAPPING_TERM 225
